name: image_quote_generator
description: A sample command-line application.
version: 1.0.0
homepage: https://www.github.com/graphicbeacon/image_quote_generator

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies: 
  aws_lambda_dart_runtime: ^1.1.0
  http: ^0.13.4
  image: ^3.1.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
